APIS = [
    {
        "url": "https://data.riksdagen.se/kalender/?org=kamm&utformat=json",
        "csv": "data/kalender.csv",
        "record_path": ["kalenderlista", "kalender"],
        "keep": ["SUMMARY", "LOCATION", "DTSTART", "DTEND", "CATEGORIES", "XRDRM", "XRDSOURCE", "XRDDOKID"],
        "rename": {
            "SUMMARY":    "titel",
            "LOCATION":   "plats",
            "DTSTART":    "start_tid",
            "DTEND":      "slut_tid",
            "CATEGORIES": "kategori",
            "XRDRM":      "riksmote",
            "XRDSOURCE":  "kalla",
            "XRDDOKID":   "dok_id",
        },
    },
    {
        "url": "https://data.riksdagen.se/personlista/?utformat=json",
        "csv": "data/ledamoter.csv",
        "record_path": ["personlista", "person"],
        "keep": ["tilltalsnamn", "efternamn", "parti", "valkrets", "status", "fodd_ar", "kon", "iort",
                 "person_url_xml", "bild_url_80"],
        "rename": {
            "tilltalsnamn": "fornamn",
            "fodd_ar":      "fodelsear",
            "iort":         "hemort",
            "status":       "riksdagsstatus",
        },
    },
    {
        "url": "https://data.riksdagen.se/dokumentlista/?sz=500&utformat=json",
        "csv": "data/dokument.csv",
        "record_path": ["dokumentlista", "dokument"],
        "keep": ["dok_id", "titel", "datum", "doktyp", "rm", "organ", "status",
                 "publicerad", "summary", "beteckning", "debattnamn"],
        "rename": {"rm": "riksmote", "doktyp": "dokumenttyp"},
    },
    {
        "url": "https://data.riksdagen.se/voteringlista/?sz=500&utformat=json",
        "csv": "data/voteringar.csv",
        "record_path": ["voteringlista", "votering"],
        "keep": ["rm", "beteckning", "punkt", "namn", "parti", "valkrets", "rost",
                 "avser", "votering", "systemdatum", "dok_id"],
        "rename": {
            "rm":          "riksmote",
            "beteckning":  "arende",
            "punkt":       "arende_punkt",
            "namn":        "ledamot_namn",
            "votering":    "voteringstyp",
            "systemdatum": "registrerat",
        },
    },
    {
        "url": "https://data.riksdagen.se/anforandelista/?sz=500&utformat=json",
        "csv": "data/anforanden.csv",
        "record_path": ["anforandelista", "anforande"],
        "keep": ["dok_id", "dok_titel", "dok_datum", "dok_rm", "talare", "parti",
                 "anforande_nummer", "replik", "systemdatum", "anforande_url_html"],
        "rename": {
            "dok_titel":        "titel",
            "dok_datum":        "datum",
            "dok_rm":           "riksmote",
            "anforande_nummer": "anforande_nr",
            "replik":           "ar_replik",
            "systemdatum":      "registrerat",
        },
    },
]